bancorprotocol/webapp-v3

src/elements/earn/portfolio/v3/pendingWithdraw/V3WithdrawCancelModal.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/V3WithdrawItem.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/confirm/useV3WithdrawConfirm.ts, src/elements/earn/portfolio/v3/pendingWithdraw/useV3Withdraw.ts, src/services/observables/pools.ts, src/services/web3/v3/portfolio/withdraw.ts, src/store/portfolio/v3Portfolio.ts, src/store/portfolio/v3Portfolio.types.ts
=> Fixes: #370 Cancel Withdraw APY

src/elements/earn/portfolio/v3/holdings/V3HoldingsItem.tsx, src/elements/earn/portfolio/v3/initWithdraw/step1/V3WithdrawStep1.tsx, src/elements/earn/portfolio/v3/initWithdraw/step2/V3WithdrawStep2.tsx, src/elements/earn/portfolio/v3/initWithdraw/step3/V3WithdrawStep3.tsx, src/elements/earn/portfolio/v3/initWithdraw/step4/V3WithdrawStep4.tsx
=> Fixes: Mobile UI issues

src/components/tokenInput/TokenInputV3.tsx, src/components/tokenInputField/TokenInputField.tsx, src/components/tokenInputPercentage/TokenInputPercentageV3.tsx, src/elements/earn/pools/addLiquidity/dual/AddLiquidityDualTokenPrices.tsx, src/elements/earn/pools/addLiquidity/empty/AddLiquidityEmptyStep1.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/liquidityProtection/claim/ClaimAvailable.tsx, src/elements/earn/portfolio/liquidityProtection/claim/ClaimLocked.tsx, src/elements/earn/portfolio/liquidityProtection/protectedPositions/MyStake.tsx, src/elements/earn/portfolio/liquidityProtection/rewards/MyRewards.tsx, src/elements/earn/portfolio/liquidityProtection/rewards/claim/RewardsClaimAmount.tsx, src/elements/earn/portfolio/v3/UpgradeBntModal.tsx, src/elements/earn/portfolio/v3/bonuses/V3BonusesModal.tsx, src/pages/earn/portfolio/MigrateProtect.tsx
=> Removed ~ symbol from USD values

src/components/tokenInputPercentage/TokenInputPercentage.tsx, src/elements/modalVbnt/ModalVbnt.tsx
=> Fixes: #371 Stake vBNT modal buttons

src/elements/earn/portfolio/v3/holdings/V3HoldingsItem.tsx
=> Fixes: #341 Holding chevron open state

src/elements/earn/portfolio/withdrawLiquidity/WithdrawLiquidityWidget.tsx
=> Fixes: #308 V2 Withdraw button

src/pages/Vote.tsx
=> Vote page text

src/elements/earn/pools/TopPools.tsx, src/services/observables/portfolio.ts, src/services/web3/v3/portfolio/standardStaking.ts
=> Top Performing

src/elements/settings/SettingsMenu.tsx
=> Slippage percentage symbol

src/elements/earn/pools/addLiquidity/empty/AddLiquidityEmptyCTA.tsx, src/elements/earn/pools/addLiquidity/single/AddLiquiditySingleCTA.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/v3/V3Portfolio.tsx, src/elements/swapLimit/SwapLimit.tsx, src/elements/swapMarket/SwapMarket.tsx, src/elements/walletConnect/WalletConnectModal.tsx, src/elements/walletConnect/useWalletConnect.ts, src/pages/Vote.tsx, src/pages/earn/portfolio/PortfolioWelcome.tsx
=> Wallet Connect

src/elements/earn/portfolio/liquidityProtection/protectedPositions/ProtectedPositionTableCellActions.tsx
=> Tooltip when migration is disabled

public/index.html
=> GTM No Script

src/elements/admin/AdminUseFork.tsx, src/router/bancorURL.service.ts, src/services/api/bancorApi/bancorApiV2.ts, src/services/api/bancorApi/bancorApiV3.ts, src/utils/localStorage.ts
/admin is now /debug
Can override API URL
=> can now set API URL

src/components/table/DataTable.tsx, src/elements/earn/portfolio/v3/holdings/V3HoldingsItemStaked.tsx, src/elements/earn/portfolio/v3/holdings/V3HoldingsItemUnstaked.tsx
=> Fixes: #400 and #383 - Styling

src/services/observables/pools.ts, src/services/web3/v3/portfolio/standardStaking.ts
=> Fixes: #422 LastProgramId Multicall

src/elements/earn/portfolio/v3/pendingWithdraw/confirm/V3WithdrawConfirmModal.tsx, src/hooks/useIsPoolStable.ts
=> Fixes: #416 Unstable Pool Withdrawal

src/services/observables/tokens.ts
=> Fixes: #449 Token USD Price 

src/components/popover/PopoverV3.tsx, src/elements/layoutHeader/LayoutHeader.tsx
=> Fixes: #445 Top Navigation / Tooltip 

src/components/button/Button.tsx, src/components/tokenInput/TokenInputV3.tsx, src/components/tokenInputPercentage/TokenInputPercentageV3.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/v3/initWithdraw/V3WithdrawModal.tsx, src/elements/earn/portfolio/withdrawLiquidity/WithdrawLiquidityWidget.tsx, src/elements/swapHeader/SwapHeader.tsx, src/elements/swapSwitch/SwapSwitch.tsx, src/elements/swapWidget/SwapWidget.tsx, src/elements/trade/TradeWidgetInput.tsx
=> No usd price

src/styles/utilities/index.css
=> Fixes: #446 Page horizontal padding

src/elements/earn/pools/poolsTable/PoolsTable.tsx
=> Fixes: #444 Earn Table column width

src/components/button/Button.tsx, src/components/tokenInput/TokenInputV3.tsx, src/components/tokenInputPercentage/TokenInputPercentageV3.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/v3/initWithdraw/V3WithdrawModal.tsx, src/elements/earn/portfolio/withdrawLiquidity/WithdrawLiquidityWidget.tsx, src/elements/swapHeader/SwapHeader.tsx, src/elements/swapSwitch/SwapSwitch.tsx, src/elements/swapWidget/SwapWidget.tsx, src/elements/trade/TradeWidgetInput.tsx
Reverts bancorprotocol/webapp-v3#437
=> Revert "No usd price"

src/services/observables/pools.ts
=> Fixes: #471 StakedBalance when trading disabled

src/components/selectPoolModal/SelectPoolModalContent.tsx, src/elements/earn/pools/TopPools.tsx, src/elements/earn/pools/poolsTable/EarnTableV2.tsx, src/elements/earn/pools/poolsTable/PoolsTable.tsx, src/elements/earn/pools/poolsTable/PoolsTableCellApr.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/v3/V3AvailableToStake.tsx, src/elements/earn/portfolio/v3/bonuses/V3BonusesModal.tsx, src/elements/earn/portfolio/v3/earningsTable/menu/V3EarningTableMenuMain.tsx, src/elements/earn/portfolio/v3/holdings/V3UnstakeModal.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/V3WithdrawCancelModal.tsx, src/pages/earn/portfolio/MigrateProtect.tsx, src/services/api/bancorApi/bancorApi.types.ts, src/services/observables/apiData.ts, src/services/observables/pools.ts, src/store/bancor/pool.ts, src/utils/formulas.ts
=> Apr change

src/services/observables/tokens.ts, src/store/bancor/token.ts
=> Available to deposit sort

src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/earn/portfolio/v3/bonuses/useV3Bonuses.ts, src/elements/earn/portfolio/v3/holdings/V3HoldingsItemUnstaked.tsx, src/elements/earn/portfolio/v3/holdings/V3UnstakeModal.tsx, src/elements/earn/portfolio/v3/initWithdraw/step3/useV3WithdrawStep3.ts, src/elements/earn/portfolio/v3/pendingWithdraw/confirm/useV3WithdrawConfirm.ts, src/elements/earn/portfolio/v3/pendingWithdraw/useV3Withdraw.ts, src/elements/trade/useTrade.ts, src/services/notifications/notifications.ts
=> Fixes: #452 Notification error handling

src/pages/Vote.tsx, src/services/observables/gov.ts, src/services/observables/triggers.ts, src/services/web3/config.ts, src/services/web3/governance/governance.ts, src/store/gov/gov.ts, src/store/index.ts
=> Vote Data Fetching

src/services/web3/swap/market.ts
=> Trade Rate

src/elements/earn/portfolio/v3/holdings/V3HoldingsItemUnstaked.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/confirm/V3WithdrawConfirmInfo.tsx
=> Fixes: #527 - Confirm withdraw text update

src/elements/earn/pools/poolsTable/EarnTableV2.tsx
=> Fixes: #551 - Tooltip text change

src/elements/admin/AdminUseFork.tsx, src/elements/admin/AdminUseMainnet.tsx, src/elements/earn/portfolio/v3/V3AvailableToStake.tsx, src/elements/tokens/TokenTable.tsx
=> Deposit trade and debug pages

src/elements/earn/portfolio/v3/holdings/V3HoldingsItem.tsx, src/services/web3/v3/portfolio/withdraw.ts
=> Withdrawal breakdown

src/elements/earn/portfolio/v3/holdings/V3HoldingsItem.tsx, src/elements/earn/portfolio/v3/initWithdraw/step1/V3WithdrawStep1.tsx, src/elements/earn/portfolio/v3/initWithdraw/step1/useV3WithdrawStep1.ts, src/elements/earn/portfolio/v3/pendingWithdraw/V3WithdrawItem.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/confirm/V3WithdrawConfirmModal.tsx, src/elements/earn/portfolio/v3/pendingWithdraw/confirm/useV3WithdrawConfirm.ts, src/services/web3/v3/portfolio/withdraw.ts, src/utils/helperFunctions.ts
=> Remove deficit warning dynamically

src/elements/earn/portfolio/v3/pendingWithdraw/confirm/V3WithdrawConfirmModal.tsx
=> warning location changed - fixes #576

src/components/navigate/Navigate.tsx, src/components/table/DataTable.tsx, src/config.ts, src/elements/earn/pools/SnapshotLink.tsx, src/elements/earn/pools/Statistics.tsx, src/elements/earn/pools/poolsTable/EarnTableV2.tsx, src/elements/earn/pools/poolsTable/PoolsTable.tsx, src/elements/settings/SettingsMenu.tsx, src/services/api/bancorApi/bancorApi.types.ts, src/services/observables/apiData.ts, src/services/observables/pools.ts, src/services/observables/statistics.ts, src/store/bancor/bancor.ts, src/store/bancor/pool.ts
=> Network fees

src/elements/earn/pools/poolsTable/PoolsTable.tsx
=> Reward filter

src/elements/earn/portfolio/v3/pendingWithdraw/confirm/V3WithdrawConfirmOutputBreakdown.tsx
=> Output breakdown

src/components/table/DataTable.tsx, src/components/table/TablePagination.tsx
=> Fixes: #522 - Table pagination: Go to page 1

src/pages/Vote.tsx
=> Fixes: #516 - How to vote link

src/components/popover/PopoverV3.tsx, src/elements/walletConnect/WalletConnectButton.tsx
=> Fixes: #590 - Wallet connect button behaviour

src/utils/formulas.ts
=> Fixes: #612 - 24h change infinity to 0

src/components/modalFullscreen/ModalFullscreen.tsx
=> Fixes: #613 - Mobile styling issue

src/components/switch/Switch.tsx, src/elements/earn/pools/poolsTable/v3/DepositFAQ.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx, src/elements/trade/TradeWidgetInput.tsx, src/services/api/bancorApi/bancorApi.types.ts, src/services/observables/apiData.ts, src/utils/v3Deposit.ts
=> Feature: Enable Deposits

src/components/table/DataTable.tsx, src/components/table/TablePagination.tsx, src/utils/localStorage.ts
=> Page rows LS

src/services/observables/pools.ts
=> Harcoded values

src/elements/earn/pools/poolsTable/v3/DepositFAQ.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx
=> Fixes: #627 - Deposit fixes

src/elements/earn/portfolio/liquidityProtection/protectedPositions/ProtectedPositionTableCellActions.tsx
=> Skipping migrate modal

src/elements/earn/portfolio/v3/UpgradeBntModal.tsx, src/elements/earn/portfolio/v3/UpgradeTknModal.tsx
=> Upgrading last position

src/elements/earn/portfolio/v3/V3AvailableToStake.tsx
=> Deposit to new pools

src/services/api/bancorApi/bancorApi.types.ts, src/services/observables/pools.ts, src/services/web3/v3/pools/pools.ts
=> Fixes: #639 - Pool Liquidity multicall

src/elements/earn/portfolio/v3/externalHoldings/V3ExternalHoldingsModal.tsx, src/elements/walletConnect/useWalletConnect.ts, src/services/web3/wallet/utils.ts
=> Support coinbase wallet mobile auto connect

src/elements/tokens/TokenTable.tsx
=> Fixes: #659 - Remove IL icon from tokens table

src/elements/earn/pools/poolsTable/PoolsTableCellActions.tsx, src/elements/earn/pools/poolsTable/v3/DepositDisabledModal.tsx, src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx
=> Fix: #670 - v2 deposit disable text

src/assets/logos/binance.svg, src/pages/Fiat.tsx
Added Binance Connect to Fiat page and Binance logo to assets.
=> Add Binance Connect and logo

src/elements/earn/pools/poolsTable/v3/DepositV3Modal.tsx
=> Fixes #677 - Hide Gift icon when APR === 0

src/components/Page.tsx, src/elements/fiat/FiatBox.tsx, src/pages/Fiat.tsx
=> Fixes #649 - Fiat Page Mobile and styling

src/pages/Swap.tsx, src/styles/base/index.css, src/styles/utilities/index.css
=> Fixes: #648 - Mobile Background styling

src/services/observables/apiData.ts, src/services/observables/pools.ts, src/services/observables/portfolio.ts, src/services/observables/tokens.ts, src/services/observables/triggers.ts, src/services/web3/v3/portfolio/helpers.ts, src/store/bancor/pool.ts, src/store/portfolio/v3Portfolio.ts
=> Portfolio All positions

src/App.tsx, src/components/WarningModal.tsx, src/utils/localStorage.ts, src/utils/pureFunctions.ts
=> Migration disable modal

src/App.tsx, src/components/table/TableCellExpander.tsx, src/elements/earn/portfolio/liquidityProtection/protectedPositions/ProtectedPositionTableCellActions.tsx, src/utils/localStorage.ts
=> Intermediate popup

src/pages/Fiat.tsx
=> #731 - remove banxa

src/pages/Fiat.tsx
=> #733 - remove simplex
